---
- name: Configure AAP role assignments
  hosts: localhost
  gather_facts: false

  vars:
    controller_hostname: "https://vm-10-1-230-16.ans.cee.ral3.lab.eng.rdu2.redhat.com"
    controller_username: "admin"
    controller_password: "admin"
    controller_validate_certs: false

    controller_role_team_assignments:
      - team: "my_team"
        role_definition: "InstanceGroup Use"
        assignment_objects:
          - name: "my-instance-group"
            type: "instance_groups"

  collections:
    - infra.aap_configuration

  tasks:

    - name: Apply team role assignments
      infra.aap_configuration.controller_role_team_assignment:
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        controller_validate_certs: "{{ controller_validate_certs }}"

        team: "{{ item.0.team }}"
        role: "{{ item.0.role_definition }}"
        target_name: "{{ item.1.name }}"
        target_type: "{{ item.1.type }}"

      loop: "{{ controller_role_team_assignments | subelements('assignment_objects') }}"
